src/minitickets/urls.py
# coding: utf-8

from django.conf.urls import patterns, url

from src.minitickets.views import FuncionarioCreateView, FuncionarioUpdateView,\
    FuncionarioListView, FuncionarioDeleteView, ProdutoCreateView, ProdutoUpdateView, ProdutoDeleteView, ProdutoListView, \
    ClienteListView, ClienteUpdateView, ClienteDeleteView, ClienteCreateView, TicketCreateView, \
    TicketListView, ClienteAutoCompleteView, TicketDetailView, TicketDesenvolvedorUpdateView, TicketTipoUpdateView, \
    HistoricoTicketCreateView, TempoTicketCreateView, TempoTicketPauseView, TicketEncerrarUpdateView, \
    TicketAnalistaUpdateView, TicketReleaseUpdateView, TicketReOpenUpdateView, DashboardView

urlpatterns = patterns('src.minitickets.views',
    # <editor-fold desc="Funcionário">
    url(r'^funcionario/add/$', FuncionarioCreateView.as_view(), name='add-funcionario'),
    url(r'^funcionario/change/(?P<pk>\d+)/$', FuncionarioUpdateView.as_view(), name='change-funcionario'),
    url(r'^funcionarios/$', FuncionarioListView.as_view(), name='list-funcionario'),
    url(r'^funcionario/delete/(?P<pk>\d+)/$', FuncionarioDeleteView.as_view(), name='delete-funcionario'),
    # </editor-fold>

    # <editor-fold desc="Produto">
    url(r'^produto/add/$',ProdutoCreateView.as_view(), name='add-produto'),
    url(r'^produto/change/(?P<pk>\d+)/$',ProdutoUpdateView.as_view(), name='change-produto'),
    url(r'^produtos/$',ProdutoListView.as_view(), name='list-produto'),
    url(r'^produto/delete/(?P<pk>\d+)/$',ProdutoDeleteView.as_view(), name='delete-produto'),
    # </editor-fold>

    # <editor-fold desc="Cliente">
    url(r'^cliente/add/$',ClienteCreateView.as_view(), name='add-cliente'),
    url(r'^cliente/change/(?P<pk>\d+)/$',ClienteUpdateView.as_view(), name='change-cliente'),
    url(r'^clientes/$',ClienteListView.as_view(), name='list-cliente'),
    url(r'^cliente/delete/(?P<pk>\d+)/$',ClienteDeleteView.as_view(), name='delete-cliente'),
    url(r'^cliente/autocomplete/$',ClienteAutoCompleteView.as_view(), name='autocomplete-cliente'),
    # </editor-fold>

    # <editor-fold desc="Ticket">
    url(r'^ticket/add/$', TicketCreateView.as_view(), name='add-ticket'),
    url(r'^tickets/$',TicketListView.as_view(), name='list-ticket'),
    url(r'^ticket/detail/(?P<pk>\d+)/$',TicketDetailView.as_view(), name='detail-ticket'),
    url(r'^tickets/change/desenvolvedor/(?P<pk>\d+)/$',TicketDesenvolvedorUpdateView.as_view(), name='change-desenvolvedor-ticket'),
    url(r'^tickets/change/analista/(?P<pk>\d+)/$',TicketAnalistaUpdateView.as_view(), name='change-analista-ticket'),
    url(r'^tickets/change/tipo/(?P<pk>\d+)/$',TicketTipoUpdateView.as_view(), name='change-tipo-ticket'),
    url(r'^ticket/reopen/(?P<pk>\d+)/$',TicketReOpenUpdateView.as_view(), name='reopen-ticket'),
    url(r'^ticket/close/(?P<pk>\d+)/$',TicketEncerrarUpdateView.as_view(), name='close-ticket'),
    url(r'^ticket/release/(?P<pk>\d+)/$',TicketReleaseUpdateView.as_view(), name='release-ticket'),
    # </editor-fold>
    
    # <editor-fold desc="HistoryTicket">
    url(r'^history/ticket/add/(?P<ticket>\d+)/$', HistoricoTicketCreateView.as_view(), name='add-historicoticket'),
    # </editor-fold>

    # <editor-fold desc="TimeTicket">
    url(r'^time/ticket/add/(?P<ticket>\d+)/$', TempoTicketCreateView.as_view(), name='add-tempoticket'),
    url(r'^time/ticket/pause/(?P<ticket>\d+)/$', TempoTicketPauseView.as_view(), name='pause-tempoticket'),
    # </editor-fold>

    # <editor-fold desc="DashBoard">
    url(r'^dashboard/$', DashboardView.as_view(), name='dashboard'),
    # </editor-fold>
)

src/urls.py
# coding: utf-8

from django.conf.urls import patterns, include, url

# from django.contrib import admin
from django.contrib.auth.views import login, logout
from src.minitickets.forms import AuthenticationForm
from src.minitickets.views import HomeView

# admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', HomeView.as_view(), name='home'),

    #url(r'^admin/', include(admin.site.urls)),

    url(r'login/$', login, name='login', kwargs={'authentication_form': AuthenticationForm}),
    url(r'logout/$', logout, name='logout'),

    url(r'^', include('src.minitickets.urls', namespace='minitickets')),
    url(r'^(?P<accesstoken>[a-zA-Z0-9+=]+)/', include('src.services.urls', namespace='services')),
)

src/minitickets/models.py
# coding: utf-8

import os
import json

from django.conf import settings
from django.contrib.auth.models import AbstractBaseUser
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.template import loader
from django.utils import timezone
from lib.utils.models.validators import CpfValidator
from src.minitickets.managers import FuncionarioManager

PERMISSIONS = json.loads(open(
    os.path.join(
        settings.BASE_DIR, 'permissions.json')
).read())


class Pessoa(models.Model):
    email = models.EmailField(unique=True)
    situacao = models.PositiveSmallIntegerField(
        choices=(
            (1, 'Ativo'),
            (2, 'Inativo')
        ),
        default=1
    )

    class Meta:
        abstract = True


class PessoaFisica(Pessoa):
    nome = models.CharField(max_length=80)
    cpf = models.CharField(max_length=14, unique=True, blank=True, null=True, validators=[CpfValidator()])
    rg = models.CharField(max_length=15, unique=True, blank=True, null=True)

    class Meta:
        abstract = True

    def save(self, *args, **kwargs):
        self.cpf = self.cpf if not self.cpf == '' else None
        self.rg = self.rg if not self.rg == '' else None
        return super(PessoaFisica, self).save(*args, **kwargs)


class Funcionario(AbstractBaseUser, PessoaFisica):
    cargo = models.PositiveSmallIntegerField(
        choices=(
            (1, u'Analista'),
            (2, u'Desenvolvedor'),
            (3, u'Gerente')
        )
    )

    nome_usuario = models.CharField(max_length=50, unique=True)
    senha = models.CharField(max_length=128, help_text='Digite sua senha neste campo.')

    USERNAME_FIELD = 'nome_usuario'
    REQUIRED_FIELDS = ['nome', 'email', 'cargo']

    objects = FuncionarioManager()

    class Meta:
        verbose_name = u'Funcionário'

    def _is_active(self):
        return self.situacao == 1

    def _set_is_active(self, value):
        self.situacao = 1 if value else 2

    is_active = property(_is_active, _set_is_active)

    def _get_password(self):
        return self.senha

    def _set_password(self, value):
        self.senha = value

    password = property(_get_password, _set_password)

    def get_full_name(self):
        return self.nome

    def get_short_name(self):
        return self.nome.split(' ')[0]

    def has_perm(self, perm, obj=None):
        user_permissions = PERMISSIONS[str(self.cargo)]
        return perm in user_permissions

    def has_perms(self, perms, obj=None):
        return all(self.has_perm(perm) for perm in perms)

    def __unicode__(self):
        return self.nome


class Produto(models.Model):
    nome = models.CharField(max_length=100)
    descricao = models.TextField('Descrição', null=True, blank=True)
    situacao = models.PositiveIntegerField(
        choices=(
            (1, u'Ativo'),
            (2, u'Inativo')
        ),
        default = 1
    )

    def __unicode__(self):
        return self.nome


# <editor-fold desc="Cliente">
class Cliente(models.Model):
    nome_fantasia = models.CharField(max_length=80, blank=True, null=True)
    razao_social = models.CharField(max_length=80, unique=True)
    cnpj = models.CharField(max_length=18, unique=True)
    inscricao_estadual = models.CharField(max_length=20, unique=True, blank=True, null=True)
    inscricao_municipal = models.CharField(max_length=20, unique=True, blank=True, null=True)
    nome_diretor = models.CharField(max_length=80, blank=True, null=True)
    email = models.EmailField()
    telefone = models.CharField(max_length=15, blank=True, null=True)
    produtos = models.ManyToManyField('Produto', blank=True, null=True)
    situacao = models.PositiveSmallIntegerField(
        choices=(
            (1, 'Ativo'),
            (2, 'Inativo')
        ),
        default=1
    )

    def __unicode__(self):
        return self.razao_social

# </editor-fold>


# <editor-fold desc="Ticket">
class Ticket(models.Model):
    cliente = models.ForeignKey('Cliente')
    produto = models.ForeignKey('Produto')
    analista = models.ForeignKey('Funcionario', null=True, blank=True, related_name='analista')
    desenvolvedor = models.ForeignKey('Funcionario', null=True, blank=True, related_name='desenvolvedor')
    titulo = models.CharField(max_length=50)
    descricao = models.TextField()
    solucao = models.TextField(u'Solução', null=True, blank=True)
    tipo = models.PositiveSmallIntegerField(
        choices=(
            (1, u'Dúvida'),
            (2, u'Erro'),
            (3, u'Sugestão')
        ), default=1
    )
    data_abertura = models.DateTimeField(auto_now_add=True)
    data_fechamento = models.DateTimeField(null=True, blank=True)
    situacao = models.PositiveIntegerField(
        choices=(
            (1, 'Aberto'),
            (2, 'Fechado'),
            (3, 'Liberado')
        ), default=1
    )
# </editor-fold>


# <editor-fold desc="HistoricoTicket">
class HistoricoTicketManager(models.Manager):
    def create_historico(self, ticket, conteudo, criado_por=None, tipo=1):
        kwargs = {'ticket': ticket, 'conteudo': conteudo, "tipo": tipo}

        if criado_por is not None:
            kwargs['criado_por'] = criado_por

        instance = self.model(**kwargs)
        instance.save()

        return instance


class HistoricoTicket(models.Model):
    data_cadastro = models.DateTimeField(auto_now_add=True)
    criado_por = models.ForeignKey('Funcionario', null=True, blank=True)
    ticket = models.ForeignKey('Ticket')
    conteudo = models.TextField()
    tipo = models.IntegerField(choices=(
        (1, u"Padrão"),
        (2, u"Comentário"),
        (3, u"Iniciar/Pausar")
    ))

    objects = HistoricoTicketManager()

    class Meta:
        ordering = ['-data_cadastro']

    def _get_icon_name(self):
        return 'warning' if self.tipo == 1 else ('comment' if self.tipo == 2 else 'clock-o')
    icon_name = property(_get_icon_name)

    def get_template(self):
        if self.tipo == 2:
            return (
                '{% load markdown_deux_tags %}{% load humanize %}{% load icon from icons %}'
                '<tr><td width="50%">{% icon icon_name "class"="text-muted bigger-120 no-padding" %}'
                '<strong> {{ criado_por }} </strong></td><td class="align-right">'
                '<em><time datetime="{{ data_cadastro|date:"Y-m-d H:i" }}">'
                '{% icon "clock-o" %} {{ data_cadastro|naturaltime }}</time></em>'
                '</td></tr><tr><td colspan="2">{{ conteudo|markdown }}</td></tr>'
            )
        else:
            return (
                '{% load markdown_deux_tags %}{% load humanize %}{% load icon from icons %}'
                '<tr><td width="50%">{% icon icon_name "class"="text-muted no-padding bigger-120" %}'
                ' {{ conteudo }}</td><td class="align-right">'
                '<em><time datetime="{{ data_cadastro|date:"Y-m-d H:i" }}">'
                '{% icon "clock-o" %} {{ data_cadastro|naturaltime }}</time></em>'
                '</td></tr><tr><td colspan="2"></td></tr>'
            )

    def render(self):
        context = loader.Context({
            'data_cadastro': self.data_cadastro,
            'conteudo': self.conteudo,
            'criado_por': self.criado_por,
            'icon_name': self.icon_name,
        })

        template = loader.get_template_from_string(self.get_template())
        return template.render(context)
# </editor-fold>


# <editor-fold desc="TempoTicket">
class TempoTicketManager(models.Manager):
    def start(self, ticket, funcionario):
        tempo_ticket = self.model(funcionario=funcionario, ticket=ticket)
        tempo_ticket.save()

        history = HistoricoTicket.objects.create_historico(
            ticket=ticket,
            conteudo="%s iniciou o ticket." % (unicode(funcionario)),
            tipo=3
        )

        return (tempo_ticket, history)

    def pause(self, tempo_ticket):
        tempo_ticket.data_termino = timezone.now()
        tempo_ticket.save()

        history = HistoricoTicket.objects.create_historico(
            ticket=tempo_ticket.ticket,
            conteudo="%s pausou o ticket." % (unicode(tempo_ticket.funcionario)),
            tipo=3
        )

        return (tempo_ticket, history)


class TempoTicket(models.Model):
    data_inicio = models.DateTimeField(auto_now_add=True)
    data_termino = models.DateTimeField(blank=True, null=True)
    ticket = models.ForeignKey('Ticket')
    funcionario = models.ForeignKey('Funcionario')

    objects = TempoTicketManager()

    def as_seconds(self):
        if not self.data_termino:
            return 0

        seconds = (self.data_termino - self.data_inicio).total_seconds()
        return round(seconds, 0) if seconds > 0 else 0

    def as_minutes(self):
        return round(self.as_seconds() / 60, 2)

    def as_hours(self):
        return round(self.as_minutes() / 60, 2)
# </editor-fold>

src/minitickets/templates/minitickets/teste.html
<div class="editable-input">
    <select class="form-control input-sm">
        Thiago Almeida
    </select>
</div>

src/minitickets/templates/minitickets/ticket_encerrar_form.html
{% extends 'forms/modal.html' %}

{% load i18n %}
{% load input from forms %}

{% block scripts %}
<script type="text/javascript">

$(function () {

    $('.modal form').on("submit", function () {

        var jqxhr = $.ajax({
            url: $(this).attr("action"),
            method: "post",
            data: $(this).serialize(),
            success: function (data) {
                window.location = data.redirect_to;
            }
        });

        jqxhr.fail(function (xhr) {
            $(".modal").html(xhr.responseText);
        });

        return false;
    });

    $(".mymarkdown").markdown({
        autofocus:false,
        savable:false
    });

});
</script>
{% endblock scripts %}

{% block content.form.fields %}

<div class="row">

    <div class="col-xs-12">

        {% input form.solucao 'template'='forms/input_vertical.html'%}

    </div>

</div>

{% endblock content.form.fields %}

src/minitickets/templates/minitickets/ticket_list.html
{% extends 'base.html' %}

{% load static from staticfiles %}
{% load django_tables2 %}
{% load i18n %}
{% load humanize %}
{% load icon from icons %}
{% load lpad from utils %}
{% load lpad from utils %}

{% block content.header %}
{% endblock content.header %}

{% block scripts %}
<script src="{% static 'js/plugin/x-editable/moment.min.js' %}"></script>
<script src="{% static 'js/plugin/x-editable/jquery.mockjax.min.js' %}"></script>
<script src="{% static 'js/plugin/x-editable/x-editable.min.js' %}"></script>
{% endblock scripts %}

{% block scripts.inline %}
<script type="text/javascript">
$(function () {

    $('.analista').each(function () {
        var self = $(this),
            url = self.data('action'),
            pk = self.data('id');

        self.editable({
            name: 'analista',
            url: url,
            pk: pk,
            container: 'body',
            ajaxOptions: {
                headers: {'X-Csrftoken': '{{ csrf_token }}'}
            },
            title: 'Selecione o analista',
            type: 'select',
            value: pk,
            source: function () {
                return {
                    {% for analista in analistas %}
                        '{{ analista.pk }}': '{{ analista }}',
                    {% endfor %}
                }
            }
        });
    }).on('click', function (e) {
        return false;
    });
    
    $('.ticket-start').on('click', function () {
        var self = $(this),
            $td = self.parent().parent();

        $.ajax({
            url: $(this).attr('href'),
            method: 'post',
            headers: {'X-CsrfToken': '{{ csrf_token }}'},
            data: null,
            success: function () {
                $('.ticket-start').removeClass('hide');
                $('.ticket-pause').addClass('hide');
                $td.find('.ticket-start').addClass('hide');
                $td.find('.ticket-pause').removeClass('hide');
            }
        });
        return false;
    });

    $('.ticket-pause').on('click', function () {
        var self = $(this),
            $td = self.parent().parent();
        $.ajax({
            url: $(this).attr('href'),
            method: 'post',
            headers: {'X-CsrfToken': '{{ csrf_token }}'},
            data: null,
            success: function () {
                $td.find('.ticket-pause').addClass('hide');
                $td.find('.ticket-start').removeClass('hide');
            }
        });
        return false;
    });
});
</script>
{% endblock scripts.inline %}

{% block content %}
<div class="inbox-nav-bar no-content-padding">

    <h1 class="page-title txt-color-blueDark hidden-tablet" style="vertical-align: top;">
        <a href="{{ request.path }}" style="color: #333; text-decoration: none;">
            <i class="fa fa-fw fa-ticket "></i>
            Tickets
        </a>
    </h1>

    {% if perms.minitickets.add_ticket %}
    <div class="btn-group hidden-desktop visible-tablet" style="vertical-align: top;">
        <button class="btn btn-default dropdown-toggle" data-toggle="dropdown">
            {% trans 'Actions' %}
            {% icon 'caret-down' %}
        </button>
        <ul class="dropdown-menu pull-left">
            <li>
                <a class="inbox-load" data-toggle="modal" href="{% url "minitickets:add-ticket" %}">
                    {% icon 'plus-circle' %}
                    {% trans 'Add Ticket' %}
                </a>
            </li>
        </ul>
    </div>
    {% endif %}

    <div class="inbox-checkbox-triggered">
        <form action="{{ request.get_full_path }}">
        <div class="input-group">
            <input placeholder="{% trans 'Search' %}" value="{{ se|default:'' }}" class="form-control" name="se" type="text" size="13">
            <div class="input-group-btn">
                <button class="btn btn-default" type="submit">
                    {% icon 'search' 'class'='icon-only' %}
                </button>
            </div>
        </div>
        </form>
    </div>

    <div class="btn-group pull-right inbox-paging">

        {% if table.page %}
            {% with table.page.paginator.count as total %}
            {% with table.page.object_list|length as count %}
                {% block pagination %}

                <a class="btn btn-default btn-sm{% if not table.page.has_previous %} disabled{% endif %}" {% if table.page.has_previous %}href="{% querystring table.prefixed_page_field=table.page.previous_page_number %}"{% endif %}>
                    <strong>
                        {% icon 'angle-left' %}
                    </strong>
                </a>

                {% for page in table.paginator.page_range %}
                <a class="btn btn-default btn-sm{% if page == table.page.number %} active{% endif %}" {% if page != table.page.number %}href="{% querystring table.prefixed_page_field=page %}"{% endif %}>
                    <strong>
                        {{ page }}
                    </strong>
                </a>
                {% endfor %}

                <a class="btn btn-default btn-sm{% if not table.page.has_next %} disabled{% endif %}" {% if table.page.has_next %}href="{% querystring table.prefixed_page_field=table.page.next_page_number %}"{% endif %}>
                    <strong>
                        {% icon 'angle-right' %}
                    </strong>
                </a>
                {% endblock pagination %}
            {% endwith %}
            {% endwith %}
        {% endif %}

    </div>

    <span class="pull-right">
        {% blocktrans with table.page.paginator.count as count and table.page.object_list|length as total %}
        <span style="line-height: 30px; ">
            <strong>{{ count }}</strong> of <strong>{{ total }}</strong>
        </span>
        {% endblocktrans %}


    </span>

</div>

<div id="inbox-content" class="inbox-body no-content-padding">

    <div class="inbox-side-bar no-padding-top">

        {% if perms.minitickets.add_ticket %}
        <a data-toggle="modal" class="btn btn-primary btn-block" href="{% url "minitickets:add-ticket" %}">
            <strong>{% icon 'plus-circle' %} {% trans 'Add Ticket' %}</strong>
        </a>
        {% endif %}

        {% if user.cargo == 3 %}
        <h6>
            Analista
        </h6>

        <div class="btn-group width-100">

            <button class="btn btn-default dropdown-toggle width-100 align-left" data-toggle="dropdown">
                <span>
                {% if a %}
                    {{ a }}
                {% else %}
                    Todos
                {% endif %}
                <span class="caret pull-right" style="margin-top: -10px;"></span>

                </span>
            </button>

            <ul class="dropdown-menu">
                <li> <a href="{% querystring without 'a' %}">Todos</a> </li>
                <li> <a href="{% querystring 'a'='i' %}">Indefinidos</a> </li>
                <li class="divider"></li>
                {% for analista in analistas %}
                <li> <a href="{% querystring "a"=analista.pk %}">{{ analista }}</a> </li>
                {% endfor %}
            </ul>

        </div>
        {% endif %}

        {% if user.cargo == 1 %}
        <h6>
            Desenvolvedor
        </h6>

        <div class="btn-group width-100">

            <button class="btn btn-default dropdown-toggle width-100 align-left" data-toggle="dropdown">
                <span>
                {% if de %}
                    {{ de }}
                {% else %}
                    Todos
                {% endif %}
                <span class="caret pull-right" style="margin-top: -10px;"></span>

                </span>
            </button>

            <ul class="dropdown-menu">
                <li> <a href="{% querystring without 'de' %}">----------</a> </li>
                <li class="divider"></li>
                {% for desenvolvedor in desenvolvedores %}
                <li> <a href="{% querystring "de"=desenvolvedor.pk %}">{{ desenvolvedor }}</a> </li>
                {% endfor %}
            </ul>

        </div>
        {% endif %}

        <hr class="simple">

        <h6>
            {% trans 'Status' %}
        </h6>

        <ul class="inbox-menu-lg">
            <li{% if s == 'open' or not s %} class="active"{% endif %}>
                <a href="{% querystring 's'='open' %}">{% trans 'Open' %}</a>
            </li>

            <li{% if s == 'closed' %} class="active"{% endif %}>
                <a href="{% querystring 's'='closed' %}">{% trans 'Closed' %}</a>
            </li>
        </ul>

        <hr class="simple">

        <h6>
            {% trans 'Types' %}
        </h6>

        <ul class="inbox-menu-lg">
            <li{% if not t %} class="active"{% endif %}>
                <a href="{% querystring without 't' %}"> {% trans 'All' %} </a>
            </li>
            <li{% if t == '1' %} class="active"{% endif %}>
                <a href="{% querystring 't'=1 %}">{% trans 'Question' %}</a>
            </li>
            <li{% if t == '2' %} class="active"{% endif %}>
                <a href="{% querystring 't'=2 %}">{% trans 'Error' %}</a>
            </li>
            <li{% if t == '3' %} class="active"{% endif %}>
                <a href="{% querystring 't'=3 %}">{% trans 'Sujestion' %}</a>
            </li>
        </ul>

    </div>

    <div class="table-wrap custom-scroll animated fast fadeInRight no-padding-top" style="height: 400px; opacity: 1;">

        <table id="inbox-table" class="table table-striped table-hover">
            <tbody>
                {% for row in table.page.object_list|default:table.rows %}
                {% with row.record as ticket %}
                <tr data-action="{% url 'minitickets:detail-ticket' ticket.pk %}" trigger="click" class="{% if ticket.situacao == 1 %}unread{% elif ticket.situacao == 3 %}success unread{% endif %}">
                    <td class="inbox-data-from hidden-xs hidden-sm">
                        <div style="padding-left: 7px;">
                            {{ ticket.pk|lpad:5 }} - {{ ticket.cliente.nome_fantasia }}
                        </div>
                    </td>
                    <td class="inbox-data-message">
                        <div>
                            <span>
                                {% if ticket.tipo == 1 %}
                                <span class="label bg-color-orange">{{ ticket.get_tipo_display }}</span>
                                {% elif ticket.tipo == 2 %}
                                <span class="label bg-color-red">{{ ticket.get_tipo_display }}</span>
                                {% elif ticket.tipo == 3 %}
                                <span class="label bg-color-blue">{{ ticket.get_tipo_display }}</span>
                                {% endif %}
                                {{ ticket.produto|truncatechars:20 }}
                            </span>
                            {{ ticket.titulo|truncatechars:50 }}
                        </div>
                    </td>
                    <td class="inbox-data-attachment hidden-xs">
                        {% if user.cargo == 3 and ticket.situacao != 2 %}
                        <div class="editable-input block">
                            <span data-id="{{ ticket.analista.id }}" data-action="{% url 'minitickets:change-analista-ticket' pk=ticket.pk %}" class="cursor-pointer analista">
                                {{ ticket.analista|default:'Indefinido' }}
                            </span>
                        </div>
                        {% elif ticket.situacao != 2 %}
                        <div>
                            <a href="{% url "minitickets:add-tempoticket" ticket=ticket.pk %}" class="ticket-start txt-color-darken{% if started_ticket.pk == ticket.pk %} hide{% endif %}" data-original-title="{% trans 'Start' %}"  data-placement="left" rel="tooltip">
                                {% icon 'play' 'class'='bigger-120' %}
                            </a>

                            <a href="{% url "minitickets:pause-tempoticket" ticket=ticket.pk %}"  class="ticket-pause txt-color-darken active{% if not started_ticket.pk == ticket.pk %} hide{% endif %}" data-original-title="{% trans 'Pause' %}" data-placement="left" rel="tooltip">
                                {% icon 'pause' 'class'='bigger-120' %}
                            </a>
                        </div>
                        {% endif %}
                    </td>
                    <td class="inbox-data-date hidden-xs align-right" style="white-space: nowrap;">

                        <div class="smaller-80 txt-color-blueLight" style="padding-right: 5px;">
                            <time datetime="{{ ticket.data_abertura|date:'Y-m-d H:i' }}">
                                {% icon 'clock-o' %}
                                {{ ticket.data_abertura|naturaltime }}
                            </time>
                        </div>

                    </td>
                </tr>
                {% endwith %}
                {% empty %}
                    <tr>
                        <td class="center">
                            {% trans 'No records found!' %}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>

    </div>

</div>
{% endblock content %}

src/minitickets/templates/minitickets/ticket_release_form.html
{% extends 'forms/modal.html' %}

{% load i18n %}
{% load input from forms %}

{% block scripts %}
<script type="text/javascript">

$(function () {

    $('.modal form').on("submit", function () {

        var jqxhr = $.ajax({
            url: $(this).attr("action"),
            method: "post",
            data: $(this).serialize(),
            success: function (data) {
                window.location = data.redirect_to;
            }
        });

        jqxhr.fail(function (xhr) {
            $(".modal").html(xhr.responseText);
        });

        return false;
    });

    $(".mymarkdown").markdown({
        autofocus:false,
        savable:false
    });

});
</script>
{% endblock scripts %}

{% block content.form.fields %}

<div class="row">

    <div class="col-xs-12">

        {% input form.historico 'template'='forms/input_vertical.html'%}

    </div>

</div>

{% endblock content.form.fields %}