src/minitickets/urls.py
# coding: utf-8

from django.conf.urls import patterns, url

from src.minitickets.views import FuncionarioCreateView, FuncionarioUpdateView,\
    FuncionarioListView, FuncionarioDeleteView, ProdutoCreateView, ProdutoUpdateView, ProdutoDeleteView, ProdutoListView, \
    ClienteListView, ClienteUpdateView, ClienteDeleteView, ClienteCreateView, TicketCreateView, \
    TicketListView, ClienteAutoCompleteView, TicketDetailView, TicketDesenvolvedorUpdateView, TicketTipoUpdateView, \
    HistoricoTicketCreateView, TempoTicketCreateView, TempoTicketPauseView, TicketEncerrarUpdateView, \
    TicketAnalistaUpdateView, TicketReleaseUpdateView, TicketReOpenUpdateView, DashboardView

urlpatterns = patterns('src.minitickets.views',
    # <editor-fold desc="Funcionário">
    url(r'^funcionario/add/$', FuncionarioCreateView.as_view(), name='add-funcionario'),
    url(r'^funcionario/change/(?P<pk>\d+)/$', FuncionarioUpdateView.as_view(), name='change-funcionario'),
    url(r'^funcionarios/$', FuncionarioListView.as_view(), name='list-funcionario'),
    url(r'^funcionario/delete/(?P<pk>\d+)/$', FuncionarioDeleteView.as_view(), name='delete-funcionario'),
    # </editor-fold>

    # <editor-fold desc="Produto">
    url(r'^produto/add/$',ProdutoCreateView.as_view(), name='add-produto'),
    url(r'^produto/change/(?P<pk>\d+)/$',ProdutoUpdateView.as_view(), name='change-produto'),
    url(r'^produtos/$',ProdutoListView.as_view(), name='list-produto'),
    url(r'^produto/delete/(?P<pk>\d+)/$',ProdutoDeleteView.as_view(), name='delete-produto'),
    # </editor-fold>

    # <editor-fold desc="Cliente">
    url(r'^cliente/add/$',ClienteCreateView.as_view(), name='add-cliente'),
    url(r'^cliente/change/(?P<pk>\d+)/$',ClienteUpdateView.as_view(), name='change-cliente'),
    url(r'^clientes/$',ClienteListView.as_view(), name='list-cliente'),
    url(r'^cliente/delete/(?P<pk>\d+)/$',ClienteDeleteView.as_view(), name='delete-cliente'),
    url(r'^cliente/autocomplete/$',ClienteAutoCompleteView.as_view(), name='autocomplete-cliente'),
    # </editor-fold>

    # <editor-fold desc="Ticket">
    url(r'^ticket/add/$', TicketCreateView.as_view(), name='add-ticket'),
    url(r'^tickets/$',TicketListView.as_view(), name='list-ticket'),
    url(r'^ticket/detail/(?P<pk>\d+)/$',TicketDetailView.as_view(), name='detail-ticket'),
    url(r'^tickets/change/desenvolvedor/(?P<pk>\d+)/$',TicketDesenvolvedorUpdateView.as_view(), name='change-desenvolvedor-ticket'),
    url(r'^tickets/change/analista/(?P<pk>\d+)/$',TicketAnalistaUpdateView.as_view(), name='change-analista-ticket'),
    url(r'^tickets/change/tipo/(?P<pk>\d+)/$',TicketTipoUpdateView.as_view(), name='change-tipo-ticket'),
    url(r'^ticket/reopen/(?P<pk>\d+)/$',TicketReOpenUpdateView.as_view(), name='reopen-ticket'),
    url(r'^ticket/close/(?P<pk>\d+)/$',TicketEncerrarUpdateView.as_view(), name='close-ticket'),
    url(r'^ticket/release/(?P<pk>\d+)/$',TicketReleaseUpdateView.as_view(), name='release-ticket'),
    # </editor-fold>
    
    # <editor-fold desc="HistoryTicket">
    url(r'^history/ticket/add/(?P<ticket>\d+)/$', HistoricoTicketCreateView.as_view(), name='add-historicoticket'),
    # </editor-fold>

    # <editor-fold desc="TimeTicket">
    url(r'^time/ticket/add/(?P<ticket>\d+)/$', TempoTicketCreateView.as_view(), name='add-tempoticket'),
    url(r'^time/ticket/pause/(?P<ticket>\d+)/$', TempoTicketPauseView.as_view(), name='pause-tempoticket'),
    # </editor-fold>

    # <editor-fold desc="DashBoard">
    url(r'^dashboard/$', DashboardView.as_view(), name='dashboard'),
    # </editor-fold>
)

src/urls.py
# coding: utf-8

from django.conf.urls import patterns, include, url

# from django.contrib import admin
from django.contrib.auth.views import login, logout
from src.minitickets.forms import AuthenticationForm
from src.minitickets.views import HomeView

# admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', HomeView.as_view(), name='home'),

    #url(r'^admin/', include(admin.site.urls)),

    url(r'login/$', login, name='login', kwargs={'authentication_form': AuthenticationForm}),
    url(r'logout/$', logout, name='logout'),

    url(r'^', include('src.minitickets.urls', namespace='minitickets')),
    url(r'^(?P<accesstoken>[a-zA-Z0-9+=]+)/', include('src.services.urls', namespace='services')),
)

src/minitickets/models.py
# coding: utf-8

import os
import json

from django.conf import settings
from django.contrib.auth.models import AbstractBaseUser
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.template import loader
from django.utils import timezone
from lib.utils.models.validators import CpfValidator
from src.minitickets.managers import FuncionarioManager

PERMISSIONS = json.loads(open(
    os.path.join(
        settings.BASE_DIR, 'permissions.json')
).read())


class Pessoa(models.Model):
    email = models.EmailField(unique=True)
    situacao = models.PositiveSmallIntegerField(
        choices=(
            (1, 'Ativo'),
            (2, 'Inativo')
        ),
        default=1
    )

    class Meta:
        abstract = True


class PessoaFisica(Pessoa):
    nome = models.CharField(max_length=80)
    cpf = models.CharField(max_length=14, unique=True, blank=True, null=True, validators=[CpfValidator()])
    rg = models.CharField(max_length=15, unique=True, blank=True, null=True)

    class Meta:
        abstract = True

    def save(self, *args, **kwargs):
        self.cpf = self.cpf if not self.cpf == '' else None
        self.rg = self.rg if not self.rg == '' else None
        return super(PessoaFisica, self).save(*args, **kwargs)


class Funcionario(AbstractBaseUser, PessoaFisica):
    cargo = models.PositiveSmallIntegerField(
        choices=(
            (1, u'Analista'),
            (2, u'Desenvolvedor'),
            (3, u'Gerente')
        )
    )

    nome_usuario = models.CharField(max_length=50, unique=True)
    senha = models.CharField(max_length=128, help_text='Digite sua senha neste campo.')

    USERNAME_FIELD = 'nome_usuario'
    REQUIRED_FIELDS = ['nome', 'email', 'cargo']

    objects = FuncionarioManager()

    class Meta:
        verbose_name = u'Funcionário'

    def _is_active(self):
        return self.situacao == 1

    def _set_is_active(self, value):
        self.situacao = 1 if value else 2

    is_active = property(_is_active, _set_is_active)

    def _get_password(self):
        return self.senha

    def _set_password(self, value):
        self.senha = value

    password = property(_get_password, _set_password)

    def get_full_name(self):
        return self.nome

    def get_short_name(self):
        return self.nome.split(' ')[0]

    def has_perm(self, perm, obj=None):
        user_permissions = PERMISSIONS[str(self.cargo)]
        return perm in user_permissions

    def has_perms(self, perms, obj=None):
        return all(self.has_perm(perm) for perm in perms)

    def __unicode__(self):
        return self.nome


class Produto(models.Model):
    nome = models.CharField(max_length=100)
    descricao = models.TextField('Descrição', null=True, blank=True)
    situacao = models.PositiveIntegerField(
        choices=(
            (1, u'Ativo'),
            (2, u'Inativo')
        ),
        default = 1
    )

    def __unicode__(self):
        return self.nome


# <editor-fold desc="Cliente">
class Cliente(models.Model):
    nome_fantasia = models.CharField(max_length=80, blank=True, null=True)
    razao_social = models.CharField(max_length=80, unique=True)
    cnpj = models.CharField(max_length=18, unique=True)
    inscricao_estadual = models.CharField(max_length=20, unique=True, blank=True, null=True)
    inscricao_municipal = models.CharField(max_length=20, unique=True, blank=True, null=True)
    nome_diretor = models.CharField(max_length=80, blank=True, null=True)
    email = models.EmailField()
    telefone = models.CharField(max_length=15, blank=True, null=True)
    produtos = models.ManyToManyField('Produto', blank=True, null=True)
    situacao = models.PositiveSmallIntegerField(
        choices=(
            (1, 'Ativo'),
            (2, 'Inativo')
        ),
        default=1
    )

    def __unicode__(self):
        return self.razao_social

# </editor-fold>


# <editor-fold desc="Ticket">
class Ticket(models.Model):
    cliente = models.ForeignKey('Cliente')
    produto = models.ForeignKey('Produto')
    analista = models.ForeignKey('Funcionario', null=True, blank=True, related_name='analista')
    desenvolvedor = models.ForeignKey('Funcionario', null=True, blank=True, related_name='desenvolvedor')
    titulo = models.CharField(max_length=50)
    descricao = models.TextField()
    solucao = models.TextField(u'Solução', null=True, blank=True)
    tipo = models.PositiveSmallIntegerField(
        choices=(
            (1, u'Dúvida'),
            (2, u'Erro'),
            (3, u'Sugestão')
        ), default=1
    )
    data_abertura = models.DateTimeField(auto_now_add=True)
    data_fechamento = models.DateTimeField(null=True, blank=True)
    situacao = models.PositiveIntegerField(
        choices=(
            (1, 'Aberto'),
            (2, 'Fechado'),
            (3, 'Liberado')
        ), default=1
    )
# </editor-fold>


# <editor-fold desc="HistoricoTicket">
class HistoricoTicketManager(models.Manager):
    def create_historico(self, ticket, conteudo, criado_por=None, tipo=1):
        kwargs = {'ticket': ticket, 'conteudo': conteudo, "tipo": tipo}

        if criado_por is not None:
            kwargs['criado_por'] = criado_por

        instance = self.model(**kwargs)
        instance.save()

        return instance


class HistoricoTicket(models.Model):
    data_cadastro = models.DateTimeField(auto_now_add=True)
    criado_por = models.ForeignKey('Funcionario', null=True, blank=True)
    ticket = models.ForeignKey('Ticket')
    conteudo = models.TextField()
    tipo = models.IntegerField(choices=(
        (1, u"Padrão"),
        (2, u"Comentário"),
        (3, u"Iniciar/Pausar")
    ))

    objects = HistoricoTicketManager()

    class Meta:
        ordering = ['-data_cadastro']

    def _get_icon_name(self):
        return 'warning' if self.tipo == 1 else ('comment' if self.tipo == 2 else 'clock-o')
    icon_name = property(_get_icon_name)

    def get_template(self):
        if self.tipo == 2:
            return (
                '{% load markdown_deux_tags %}{% load humanize %}{% load icon from icons %}'
                '<tr><td width="50%">{% icon icon_name "class"="text-muted bigger-120 no-padding" %}'
                '<strong> {{ criado_por }} </strong></td><td class="align-right">'
                '<em><time datetime="{{ data_cadastro|date:"Y-m-d H:i" }}">'
                '{% icon "clock-o" %} {{ data_cadastro|naturaltime }}</time></em>'
                '</td></tr><tr><td colspan="2">{{ conteudo|markdown }}</td></tr>'
            )
        else:
            return (
                '{% load markdown_deux_tags %}{% load humanize %}{% load icon from icons %}'
                '<tr><td width="50%">{% icon icon_name "class"="text-muted no-padding bigger-120" %}'
                ' {{ conteudo }}</td><td class="align-right">'
                '<em><time datetime="{{ data_cadastro|date:"Y-m-d H:i" }}">'
                '{% icon "clock-o" %} {{ data_cadastro|naturaltime }}</time></em>'
                '</td></tr><tr><td colspan="2"></td></tr>'
            )

    def render(self):
        context = loader.Context({
            'data_cadastro': self.data_cadastro,
            'conteudo': self.conteudo,
            'criado_por': self.criado_por,
            'icon_name': self.icon_name,
        })

        template = loader.get_template_from_string(self.get_template())
        return template.render(context)
# </editor-fold>


# <editor-fold desc="TempoTicket">
class TempoTicketManager(models.Manager):
    def start(self, ticket, funcionario):
        tempo_ticket = self.model(funcionario=funcionario, ticket=ticket)
        tempo_ticket.save()

        history = HistoricoTicket.objects.create_historico(
            ticket=ticket,
            conteudo="%s iniciou o ticket." % (unicode(funcionario)),
            tipo=3
        )

        return (tempo_ticket, history)

    def pause(self, tempo_ticket):
        tempo_ticket.data_termino = timezone.now()
        tempo_ticket.save()

        history = HistoricoTicket.objects.create_historico(
            ticket=tempo_ticket.ticket,
            conteudo="%s pausou o ticket." % (unicode(tempo_ticket.funcionario)),
            tipo=3
        )

        return (tempo_ticket, history)


class TempoTicket(models.Model):
    data_inicio = models.DateTimeField(auto_now_add=True)
    data_termino = models.DateTimeField(blank=True, null=True)
    ticket = models.ForeignKey('Ticket')
    funcionario = models.ForeignKey('Funcionario')

    objects = TempoTicketManager()

    def as_seconds(self):
        if not self.data_termino:
            return 0

        seconds = (self.data_termino - self.data_inicio).total_seconds()
        return round(seconds, 0) if seconds > 0 else 0

    def as_minutes(self):
        return round(self.as_seconds() / 60, 2)

    def as_hours(self):
        return round(self.as_minutes() / 60, 2)
# </editor-fold>

templates/base.html
{% extends 'page.html' %}

{% load static from staticfiles %}
{% load icon from icons %}
{% load i18n %}
{% load menu from menu %}

{% block page %}

<header id="header">

    <!-- collapse menu button -->
    <div id="hide-menu" class="btn-header pull-left visible-sm visible-xs" style="width: auto; margin-left: 10px;">
        <span> <a href="javascript:void(0);" data-action="toggleMenu" title="Collapse Menu">{% icon 'reorder' %}</a> </span>
    </div>
    <!-- end collapse menu -->

    <div id="logo-group">

        <!-- PLACE YOUR LOGO HERE -->
        <span id="logo" class="bolder">
            <img src="{% static 'img/logo-wide-white.png' %}" alt="MiniTickets" class="no-margin"/>
        </span>
        <!-- END LOGO PLACEHOLDER -->

    </div>

    <!-- #PROJECTS: projects dropdown -->
    <div class="project-context pull-right">

        <span class="label">{% trans 'Welcome,' %}</span>
        <span class="project-selector dropdown-toggle" data-toggle="dropdown">{{ user.get_full_name }} {% icon 'caret-down' %}</span>

        <!-- Suggestion: populate this list with fetch and push technique -->
        <ul class="dropdown-menu">
            <li>
                <a href="{% url 'logout' %}">{% icon 'power-off' %} {% trans 'Logout' %}</a>
            </li>
        </ul>
        <!-- end dropdown-menu-->

    </div>
    <!-- end projects dropdown -->

</header> <!-- /.header -->

<aside id="left-panel">

    <!-- NAVIGATION : This navigation is also responsive

    To make this navigation dynamic please make sure to link the node
    (the reference to the nav > ul) after page load. Or the navigation
    will not initialize.
    -->
    <nav>
        <!-- NOTE: Notice the gaps after each icon usage <i></i>..
        Please note that these links work a bit different than
        traditional href="" links. See documentation for details.
        -->

        <ul>
            {% menu %}
        </ul>

    </nav>

</aside> <!-- /.menu -->

<div id="main" role="main">

    {% block page.breadcrumbs %}
    <div id="ribbon" class="breadcrumbs breadcrumbs-fixed">

        <ul class="breadcrumb">
            {% for breadcrumb in BREADCRUMBS %}
                {% block page.breadcrumbs.breadcrumb %}
                <li {% if breadcrumb.breadcrumb == BREADCRUMBS.last %}class="active"{% endif %}>
                    {{ breadcrumb.breadcrumb.icon.as_html }}
                    {% if breadcrumb.breadcrumb.url %}
                        <a href="{{ breadcrumb.breadcrumb.url }}">{{ breadcrumb.breadcrumb }}</a>
                    {% else %}
                        {{ breadcrumb.breadcrumb }}
                    {% endif %}
                </li>
                {% endblock page.breadcrumbs.breadcrumb %}
            {% endfor %}
        </ul><!-- /.breadcrumb -->

        {% block page.breadcrumbs.extra %}{% endblock page.breadcrumbs.extra %}

    </div>
    {% endblock page.breadcrumbs %}

    <div id="content">

        <!-- row -->
        <div class="row">

            <div class="col-sm-12 col-xs-12">
            {% block content.header %}
            {% if TITLE %}
            <div class="page-header">

                <h1 class="txt-color-blueDark">

                    <!-- PAGE HEADER -->
                    {{ TITLE|safe }}
                    {% if SUBTITLE %}
                    <small>
                        {% icon 'angle-double-right' %}&nbsp;&nbsp;
                        {{ SUBTITLE|safe }}
                    </small>
                    {% endif %}
                </h1>

            </div>
            {% endif %}
            {% endblock content.header %}
            </div>

        </div>
        <!-- end row -->

        <div class="row">

            <div class="col-sm-12 col-xs-12">

                {% block page.content.messages %}
                <div id="messages">
                    {% for message in messages %}
                        <div class="alert alert-block {{ message.tag }} {{ message.extra_tags }} fade in">
                            <button class="close" data-dismiss="alert" type="button">×</button>
                            {{ message|safe }}
                        </div>
                    {% endfor %}
                </div>
                {% endblock page.content.messages %}

            </div>

        </div>

        {% block content %}{% endblock content %}

    </div> <!-- /.content -->

</div>

{% endblock page %}

templates/home.html
{% extends 'base.html' %}

{% load i18n %}
{% load icon from icons %}
{% load lpad from utils %}

{% block content %}
{% if user.cargo == 3 %}
<div class="row">

    <div class="col-sm-3">
        <div class="panel">
            <div class="panel-header bg-color-gray-dark">
                <div class="row">
                    <div class="col-xs-3">
                        {% icon 'ticket' 'class'='fa-5x' %}
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="bigger-220">{{ resumo.tickets|lpad:2 }}</div>
                        <p class="no-margin">Tickets</p>
                    </div>
                </div>
            </div>
            <a href="{% url 'minitickets:list-ticket' %}" class="panel-footer bg-color-gray clearfix block no-border-top">
                <span class="pull-left">Ver todos</span>
                <span class="pull-right">{% icon 'chevron-circle-right' %}</span>
            </a>
        </div>
    </div>

    <div class="col-sm-3">
        <div class="panel">
            <div class="panel-header bg-color-gray-dark">
                <div class="row">
                    <div class="col-xs-3">
                        {% icon 'building' 'class'='fa-5x' %}
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="bigger-220">{{ resumo.clientes|lpad:2 }}</div>
                        <p class="no-margin">Clientes</p>
                    </div>
                </div>
            </div>
            <a href="{% url 'minitickets:list-cliente' %}" class="panel-footer bg-color-gray clearfix block no-border-top">
                <span class="pull-left">Ver todos</span>
                <span class="pull-right">{% icon 'chevron-circle-right' %}</span>
            </a>
        </div>
    </div>

    <div class="col-sm-3">
        <div class="panel">
            <div class="panel-header bg-color-gray-dark">
                <div class="row">
                    <div class="col-xs-3">
                        {% icon 'user' 'class'='fa-5x' %}
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="bigger-220">{{ resumo.funcionarios|lpad:2 }}</div>
                        <p class="no-margin">Funcionários</p>
                    </div>
                </div>
            </div>
            <a href="{% url 'minitickets:list-funcionario' %}" class="panel-footer bg-color-gray clearfix block no-border-top">
                <span class="pull-left">Ver todos</span>
                <span class="pull-right">{% icon 'chevron-circle-right' %}</span>
            </a>
        </div>
    </div>

    <div class="col-sm-3">
        <div class="panel">
            <div class="panel-header bg-color-gray-dark">
                <div class="row">
                    <div class="col-xs-3">
                        {% icon 'puzzle-piece' 'class'='fa-5x' %}
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="bigger-220">{{ resumo.produtos|lpad:2 }}</div>
                        <p class="no-margin">Produtos</p>
                    </div>
                </div>
            </div>
            <a href="{% url 'minitickets:list-produto' %}" class="panel-footer bg-color-gray clearfix block no-border-top">
                <span class="pull-left">Ver todos</span>
                <span class="pull-right">{% icon 'chevron-circle-right' %}</span>
            </a>
        </div>
    </div>

</div>
{% endif %}


<div class="row">

    <div class="col-sm-12">

        <div class="jarviswidget jarviswidget-color-blueDark jarviswidget-sortable" role="widget">
            <header role="heading">
                <span class="widget-icon">
                    <i class="fa fa-ticket"></i>
                </span>
                <h2>Tickets</h2>
            </header>
            <div role="content">
                <div class="widget-body no-padding">

                    <div class="table-responsive">
                        <table class="table table-bordered">
                            <thead>
                            <tr>
                                <th width="60px"></th>
                                <th>Cliente</th>
                                <th>Titulo</th>
                                <th width="100px">Situação</th>
                                <th width="60px"></th>
                            </tr>
                            </thead>

                            <tbody>
                            {% for ticket in tickets %}
                                <tr>
                                    <td class="align-center">{{ ticket.id|lpad:'5' }}</td>
                                    <td>{{ ticket.cliente }}</td>
                                    <td>{{ ticket.titulo }}</td>
                                    <td class="align-center">
                                        {% if ticket.situacao == 1 %}
                                            <span class="badge bg-color-blue">{{ ticket.get_situacao_display }}</span>
                                        {% elif ticket.situacao == 2 %}
                                            <span class="badge bg-color-green">{{ ticket.get_situacao_display }}</span>
                                        {% endif %}
                                    </td>
                                    <td class="no-padding-bottom align-center">
                                        <a href="{% url 'minitickets:detail-ticket' pk=ticket.id %}" class="btn btn-default btn-xs" rel="tooltip" data-original-title="{% trans 'Show details' %}">
                                            {% icon 'search-plus' %}
                                        </a>
                                    </td>
                                </tr>
                            {% empty %}
                                <tr>
                                    <td colspan="5" class="no-padding">
                                        <div class="well bigger-160 align-center no-border">
                                            <p class="text-muted no-margin">{% trans 'No records found!' %}</p>
                                        </div>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>

                    <div class="widget-body-toolbar">
                        <div class="row">
                            <div class="col-xs-9 col-sm-5 col-md-5 col-lg-5"></div>
                            <div class="col-xs-3 col-sm-7 col-md-7 col-lg-7 text-right">
                                <a href="{% url 'minitickets:list-ticket' %}" rel="tooltip" data-original-title="{% trans 'Show all' %}" class="btn btn-default">
                                    <i class="fa fa-search-plus"></i>
                                    <span class="hidden-mobile">{% trans 'Show all' %}</span>
                                </a>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>

    </div>

</div>

{% endblock content %}

templates/modal.html
{% block scripts.template %}{% endblock scripts.template %}
{% block scripts %}{% endblock scripts %}

<div class="modal-dialog">

	{% block modal %}
	<div class="modal-content">

		{% block modal.header %}
		<div class="modal-header">

			<button class="close" data-dismiss="modal" type="button">×</button>

			{% block modal.header.title %}
			<h4>{{ TITLE|safe }}</h4>
			{% endblock modal.header.title %}

		</div>
		{% endblock modal.header %}

		{% block modal.body %}
		<div class="modal-body">
			{% block modal.body.content %}{% endblock modal.body.content %}
		</div>
		{% endblock modal.body %}

		{% block modal.footer %}{% endblock modal.footer %}

	</div>
	{% endblock modal %}

</div>

templates/page.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html lang="pt-br">

<head>

    <meta charset="utf-8">

    <title> SmartAdmin </title>
    <meta name="description" content="">
    <meta name="author" content="">

    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">

    <!-- #CSS Links -->
    <!-- Basic Styles -->
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/smart-classes.min.css' %}">

    <!-- SmartAdmin Styles : Please note (smartadmin-production.css) was created using LESS variables -->
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/smartadmin-production.min.css' %}">
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/smartadmin-skins.min.css' %}">

    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/panel.css' %}">
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/app.css' %}">
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/forms.css' %}">

    {% block styles.base %}{% endblock styles.base %}
    {% block styles %}{% endblock styles %}

    <!-- #GOOGLE FONT -->
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,300,400,700">

</head>

<body class="smart-style-3 menu-on-top container">

    {# Page definition #}
    {% block page %}{% endblock page %}

    <!-- Scripts -->

    <!-- JQuery -->
    <script src="{% static 'js/libs/jquery-2.0.2.min.js' %}"></script>
    <script src="{% static 'js/libs/jquery-ui-1.10.3.min.js' %}"></script>

    <!-- MarkDown -->
    <script src="{% static 'js/plugin/markdown/markdown.min.js'%}"></script>
    <script src="{% static 'js/plugin/markdown/to-markdown.min.js' %}"></script>
    <script src="{% static 'js/plugin/markdown/bootstrap-markdown.min.js'%}"></script>

    <!-- Config -->
    <script src="{% static 'js/app.config.js' %}"></script>
    <script src="{% static 'js/app.js' %}"></script>

    <!-- Bootstrap -->
    <script src="{% static 'js/bootstrap/bootstrap.min.js' %}"></script>

    <!-- Page scripts content -->
    {% block scripts.base %}{% endblock scripts.base %}
    {% block scripts %}{% endblock scripts %}

    <!-- Inline page scripts content -->
    {% block scripts.inline.base %}{% endblock scripts.inline.base %}
    {% block scripts.inline %}{% endblock scripts.inline %}

</body>

</html>

templates/teste-modal.html
{% load icon from icons %}

<div class="modal-dialog">

    <div class="modal-content">

        <div class="modal-header">

            <button class="close" aria-hidden="true" data-dismiss="modal" type="button"> × </button>

            <h3 class="modal-title lighter">Modal Title</h3>

        </div>

        <div class="modal-body">


            <p>Hello modal!!</p>

        </div>

    </div>

</div>